apiVersion: v1
kind: Service
metadata:
  name: appointment-scheduling-service
spec:
  type: LoadBalancer
  selector:
    app: appointment-scheduling-service
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  
