apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-record-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-record-service
  template:
    metadata:
      labels:
        app: patient-record-service
    spec:
      containers:
      - name: patient-record-service
        image: patient-record-service:latest # built image name
        imagePullPolicy: Never # Don't try to pull image from registry
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb+srv://e17299:gFH00zihG8Pjj0pX@meditrack.wg7uo.mongodb.net/?retryWrites=true&w=majority&appName=Meditrack"
