apiVersion: v1
kind: Service
metadata:
  name: patient-record-service
spec:
  type: NodePort
  selector:
    app: patient-record-service
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30001

