apiVersion: batch/v1
kind: CronJob
metadata:
  name: redshift-analytics-cronjob
spec:
  schedule: "0 4 * * *" # Runs daily at 4 AM
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: redshift-analytics
        spec:
          containers:
          - name: redshift-analytics
            image: redshift-analytics:latest
            imagePullPolicy: Never
            env:
              - name: REDSHIFT_HOST
                value: "myredshiftcluster.csqajvgqkn5v.us-east-1.redshift.amazonaws.com"
              - name: REDSHIFT_PORT
                value: "5439"
              - name: REDSHIFT_USER
                value: "admin"
              - name: REDSHIFT_PASSWORD
                value: "E17299$sde"
              - name: REDSHIFT_DBNAME
                value: "analyticsdb"
              - name: MONGO_URI
                value: "mongodb+srv://e17299:gFH00zihG8Pjj0pX@meditrack.wg7uo.mongodb.net/?retryWrites=true&w=majority&appName=Meditrack"
          restartPolicy: OnFailure
