apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: NodePort
  selector:
    app: notification-service
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
    nodePort: 30003

