name: MediTrack CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Dependencies
      - name: Install Dependencies
        run: |
          echo "Installing only necessary dependencies..."
          sudo apt-get update
          sudo apt-get install -y apt-transport-https curl conntrack socat
          echo "Dependencies installed."

      # Step 3: Install Minikube
      - name: Install Minikube
        run: |
          echo "Installing Minikube..."
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          echo "Minikube installed."

      # Step 4: Start Minikube
      - name: Start Minikube
        run: |
          echo "Starting Minikube with Docker driver..."
          minikube start --driver=docker
          minikube addons enable ingress
          echo "Minikube started and ingress enabled."

      # Step 5: Build Docker Images
      - name: Build Docker Images
        run: |
          eval $(minikube docker-env)
          services=("PatientRecordService" "AnalyticsService" "AppointmentSchedulingService" "NotificationService" "RedshiftAnalyticsService")
          for service in "${services[@]}"; do
            echo "Building Docker image for $service..."
            docker build -t "$service:latest" -f "./$service/docker/Dockerfile" .
          done
          echo "Docker images built successfully."

      # Step 6: Deploy to Kubernetes
      - name: Deploy Kubernetes Resources
        run: |
          services=("PatientRecordService" "AnalyticsService" "AppointmentSchedulingService" "NotificationService" "RedshiftAnalyticsService")
          for service in "${services[@]}"; do
            echo "Applying Kubernetes manifests for $service..."
            kubectl apply -f "./$service/manifests/deployment.yaml"
            kubectl apply -f "./$service/manifests/service.yaml"
          done
          echo "Applying ingress..."
          kubectl apply -f ./ingress.yaml
          echo "Deployment completed."

      # Step 7: Verify Deployment
      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get services
          kubectl get ingress
