name: MediTrack CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Required Tools
      - name: Install Minikube, Conntrack, and Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https curl conntrack socat software-properties-common docker.io
          echo "Dependencies installed."

      # Step 3: Start Minikube
      - name: Start Minikube
        run: |
          echo "Starting Minikube with the Docker driver..."
          minikube start --driver=docker
          minikube addons enable ingress
          echo "Minikube started and ingress enabled."

      # Step 4: Build Docker Images
      - name: Build Docker Images for Services
        run: |
          eval $(minikube docker-env)
          services=("PatientRecordService" "AnalyticsService" "AppointmentSchedulingService" "NotificationService" "RedshiftAnalyticsService")
          for service in "${services[@]}"; do
            echo "Building Docker image for $service..."
            docker build -t "$service:latest" -f "./$service/docker/Dockerfile" .
          done
          echo "Docker images built successfully."

      # Step 5: Apply Kubernetes Manifests
      - name: Deploy Services to Kubernetes
        run: |
          services=("PatientRecordService" "AnalyticsService" "AppointmentSchedulingService" "NotificationService" "RedshiftAnalyticsService")
          for service in "${services[@]}"; do
            echo "Deploying $service to Kubernetes..."
            kubectl apply -f "./$service/manifests/deployment.yaml"
            kubectl apply -f "./$service/manifests/service.yaml"
          done
          echo "Deploying ingress..."
          kubectl apply -f ./ingress.yaml
          echo "All services deployed successfully."

      # Step 6: Verify Deployment
      - name: Verify Deployment
        run: |
          echo "Fetching Kubernetes resources..."
          kubectl get pods
          kubectl get services
          kubectl get ingress
          echo "Deployment verification completed."
