name: MediTrack CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Install Dependencies
    - name: Install Minikube and Dependencies
      run: |
        # Install required tools
        sudo apt-get update
        sudo apt-get install -y apt-transport-https curl conntrack socat software-properties-common

        # Remove the outdated Kubernetes repo and add the correct one
        sudo rm /etc/apt/sources.list.d/kubernetes.list
        echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update

        # Install cri-tools and Docker
        sudo apt-get install -y cri-tools
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

        # Add user to the Docker group
        sudo usermod -aG docker $USER

        # Install Minikube
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/
        minikube version

    # Step 3: Start Minikube
    - name: Start Minikube
      run: |
        sudo minikube start --driver=none
        sudo minikube addons enable ingress

    # Step 4: Apply Ingress Controller
    - name: Apply Ingress Controller
      run: |
        kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml

    # Step 5: Build Docker Images
    - name: Build Docker Images
      run: |
        for service in AppointmentSchedulingService NotificationService PatientRecordService AnalyticsService RedshiftAnalyticsService; do
          docker build -t $service:latest ./services/$service/docker/
        done

    # Step 6: Apply Kubernetes Manifests
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./services/AppointmentSchedulingService/manifests/
        kubectl apply -f ./services/NotificationService/manifests/
        kubectl apply -f ./services/PatientRecordService/manifests/
        kubectl apply -f ./services/AnalyticsService/manifests/
        kubectl apply -f ./services/RedshiftAnalyticsService/manifests/
        kubectl apply -f ./manifests/ingress.yaml

    # Step 7: Run Unit Tests
    - name: Run Tests
      run: |
        # Install Python and pip
        sudo apt-get install -y python3 python3-pip

        # Install dependencies
        pip3 install -r ./requirements.txt

        # Run the test suite
        python3 ./test.py
