name: MediTrack CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Restart Minikube
      - name: Restart Minikube
        run: |
          echo "Restarting Minikube..."
          minikube stop || true
          minikube start --driver=none
          minikube addons enable ingress
          echo "Minikube restarted and ingress enabled."

      # Step 3: Build Docker Images
      - name: Build Docker Images
        run: |
          eval $(minikube docker-env)  # Use Minikube's Docker daemon
          for service in AppointmentSchedulingService NotificationService PatientRecordService AnalyticsService RedshiftAnalyticsService; do
            docker build -t $service:latest ./services/$service/docker/
          done

      # Step 4: Apply Kubernetes Manifests
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./services/AppointmentSchedulingService/manifests/
          kubectl apply -f ./services/NotificationService/manifests/
          kubectl apply -f ./services/PatientRecordService/manifests/
          kubectl apply -f ./services/AnalyticsService/manifests/
          kubectl apply -f ./services/RedshiftAnalyticsService/manifests/
          kubectl apply -f ./manifests/ingress.yaml
          echo "Kubernetes manifests applied successfully."

      # Step 5: Test Deployment
      - name: Verify Deployment
        run: |
          echo "Testing deployment..."
          kubectl get pods --all-namespaces
          kubectl get services
          kubectl get ingress
