name: MediTrack CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version

      # Step 3: Build Docker Images
      - name: Build Docker Images
        run: |
          for service in AppointmentSchedulingService NotificationService PatientRecordService AnalyticsService RedshiftAnalyticsService; do
            docker build -t $service:latest ./services/$service/docker/
          done

      # Step 4: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./services/AppointmentSchedulingService/manifests/
          kubectl apply -f ./services/NotificationService/manifests/
          kubectl apply -f ./services/PatientRecordService/manifests/
          kubectl apply -f ./services/AnalyticsService/manifests/
          kubectl apply -f ./services/RedshiftAnalyticsService/manifests/
          kubectl apply -f ./manifests/ingress.yaml

      # Step 5: Run Basic Tests
      - name: Run Tests
        run: |
          echo "Running tests..."
          # Add your custom test commands below, e.g.:
          python3 ./test.py
